"""Create Profile fields firstname and lastname

Revision ID: 2be820a423f5
Revises: 2a0b59028166
Create Date: 2025-04-11 21:28:43.426405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2be820a423f5'
down_revision: Union[str, None] = '2a0b59028166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('firstname', sa.String(length=50), nullable=False))
    op.add_column('profiles', sa.Column('lastname', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'lastname')
    op.drop_column('profiles', 'firstname')
    # ### end Alembic commands ###
