"""Removing unique contraint from author_id in Posts

Revision ID: 6da375e439aa
Revises: 09fd5f085537
Create Date: 2025-04-15 00:21:29.570595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6da375e439aa'
down_revision: Union[str, None] = '09fd5f085537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_author_id_key', 'posts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('posts_author_id_key', 'posts', ['author_id'])
    # ### end Alembic commands ###
